name: say hello
on: pull_request
jobs:
  greet-universe:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: 'echo "Hello Universe! Love from ${{ github.repository }}!"'
