name: say hello
on: push
jobs:
  greet-universe:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: 'echo "Hello Universe from ${{ github.repository }}"'
